import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from '@/components/layouts/header'
import Footer from '@/components/layouts/footer'
import { AuthProvider } from '@/contexts/AuthContext'
import "./globals.css";

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modals
}: Readonly<{
  children: React.ReactNode;
  modals?: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={`${roboto.variable} antialiased`}>
        <AuthProvider>
          <div className="Toastify" />
          <Header />
            {children}
            {modals} 
          <Footer />
          </AuthProvider>
      </body>
    </html>
  );
}
